# This is a basic workflow to help you get started with Actions

name: Build Padavan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 安装依赖
        run: |
          sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
          fakeroot kmod cpio git python-docutils gettext automake autopoint \
          texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin -y

      # Runs a single command using the runners shell
      - name: 下载源码
        run: git clone --depth=1 https://github.com/dream10201/rt-n56u.git /opt/rt-n56u

      # Runs a set of commands using the runners shell
      - name: 准备工具链
        run: |
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh
      - name: 修改配置
        run: |
          ##################删除start######################
          sed -i '/CONFIG_FIRMWARE_ENABLE_IPV6=/d' $cpath
          sed -i '/CONFIG_FIRMWARE_INCLUDE_QOS=/d' $cpath
          sed -i '/CONFIG_FIRMWARE_INCLUDE_LANG_CN=/d' $cpath
          sed -i '/CONFIG_FIRMWARE_INCLUDE_TCPDUMP=/d' $cpath
          sed -i '/CONFIG_FIRMWARE_INCLUDE_QOS=/d' $cpath
          sed -i '/CONFIG_FIRMWARE_INCLUDE_QOS=/d' $cpath
          sed -i '/CONFIG_FIRMWARE_INCLUDE_QOS=/d' $cpath
          sed -i '/CONFIG_FIRMWARE_INCLUDE_QOS=/d' $cpath
          sed -i '/CONFIG_FIRMWARE_INCLUDE_QOS=/d' $cpath
          ##################删除end########################
          
          echo "CONFIG_FIRMWARE_ENABLE_IPV6=y" >> $cpath # ipv6支持
          echo "CONFIG_FIRMWARE_INCLUDE_QOS=y" >> $cpath # 带宽管理
          echo "CONFIG_FIRMWARE_INCLUDE_LANG_CN=y" >> $cpath # 中文
          echo "CONFIG_FIRMWARE_INCLUDE_TCPDUMP=y" >> $cpath # tcpdump 抓包工具
          echo "CONFIG_FIRMWARE_INCLUDE_LANG_CN=y" >> $cpath # 中文
          echo "CONFIG_FIRMWARE_INCLUDE_LANG_CN=y" >> $cpath # 中文
          echo "CONFIG_FIRMWARE_INCLUDE_LANG_CN=y" >> $cpath # 中文
          
        env:
          cpath: /opt/rt-n56u/trunk/templates/R2100.config 
      - name: 编译
        run: |
          cd /opt/rt-n56u/trunk
          ./clear_tree
          fakeroot ./build_firmware_modify R2100 
      - name : 打包发布
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Padavan-packages
          path: /opt/rt-n56u/trunk/configs/templates
